name: pr

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: r.planetary-quantum.com/quantum-public/${{ github.repository }}
    - uses: docker/build-push-action@v4
      with:
        context: rootfs
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
