name: pr

on:
  pull_request:

jobs:
  check:
    permissions:
      security-events: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6

  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: updatecli/updatecli-action@7fea18dfb6a2d7077cd040e48ed658009bee5c6f # v2
      - run: updatecli pipeline diff --config ./updatecli/updatecli.d
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: docker/github-builder/.github/workflows/build.yml@70ac3fc303efa83d2b94905e6ab78bb83cbdc2ae # v1.11.0
    permissions:
      contents: read
      id-token: write
    with:
      context: rootfs
      output: image
      push: false
      meta-images: |
        r.planetary-quantum.com/quantum-public/caddy
        ghcr.io/hostwithquantum/quantum-caddy