name: pr

on: pull_request

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: updatecli/updatecli-action@v2
    - run: updatecli diff --config ./updatecli/updatecli.d
      env:
        UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
        UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          r.planetary-quantum.com/quantum-public/caddy
          ghcr.io/hostwithquantum/quantum-caddy
    - uses: docker/build-push-action@v6
      with:
        context: rootfs
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
