name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v2
      with:
        registry: r.planetary-quantum.com
        username: ${{ secrets.QUANTUM_REGISTRY_USERNAME }}
        password: ${{ secrets.QUANTUM_REGISTRY_PASSWORD }}
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: r.planetary-quantum.com/quantum-public/${{ github.repository }}
    - uses: docker/build-push-action@v4
      with:
        context: rootfs/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
