name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v5
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@v3
      with:
        registry: r.planetary-quantum.com
        username: ${{ secrets.QUANTUM_REGISTRY_USERNAME }}
        password: ${{ secrets.QUANTUM_REGISTRY_PASSWORD }}
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          r.planetary-quantum.com/quantum-public/caddy
          ghcr.io/hostwithquantum/quantum-caddy
    - uses: docker/build-push-action@v6
      with:
        context: rootfs/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
